name: job 1

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: select the environment
        required: true
        default: qual
        options:
         - qual
         - cert
env:
    ARN_NAME: 'AWS_CERT_ENV'
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: echo "Hello from job1 ${{env.ARN_NAME}}"
       
  job2:
    needs: job1
    if: ${{ github.event.inputs.environment == 'cert'}}
    uses:  shubhamPatkar/Smart-Parking/.github/workflows/job2.yml@main
    
  job3:
    needs: job2
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: echo "Hello from job3 ${{env.ARN_NAME}}"
        
#     with:
#       ARN_Name: AWS_cert_Name
#     runs-on: [ubuntu-latest]
#     steps:
#       - name: Step1
#         run: echo "hello from job1" 
  
#       - name: Call job2 
#         uses:  shubhamPatkar/Smart-Parking/.github/workflows/job2.yml@main
       
