name: job 1

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choise
        description: select the environment
        required: true
        default: qual
        options:
         - qual
         - cert

jobs:
  job2:
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: echo "Hello from job1"
       
  job1:
    needs: job2
    if: ${{ github.event.inputs.environment == 'cert'}}
    uses:  shubhamPatkar/Smart-Parking/.github/workflows/job2.yml@main
    with:
      ARN_Name: AWS_cert_Name
#     runs-on: [ubuntu-latest]
#     steps:
#       - name: Step1
#         run: echo "hello from job1" 
  
#       - name: Call job2 
#         uses:  shubhamPatkar/Smart-Parking/.github/workflows/job2.yml@main
       
