name: job 1

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: select the environment
        required: true
        default: qual
        options:
         - qual
         - cert
env:
    ARN_NAME: ${{ if eq(github.event_name, 'push') }}value1${{ else }}value2${{ endif }}
    other_env: cert
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: |
          echo "Hello from job1 ${{env.ARN_NAME}}"
          echo "other env is ${{env.other_env}}"
       
  job2:
    needs: job1
    if: ${{ github.event.inputs.environment == 'cert'}}
    uses:  shubhamPatkar/Smart-Parking/.github/workflows/job2.yml@main
    
  job3:
    needs: job2
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: |
          echo "Hello from job3 ${{env.ARN_NAME}}"
          echo "other env is ${{env.other_env}}"
          
  job4:
    needs: job3
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: |
          echo "Hello from job3 ${{env.ARN_NAME}}"
          echo "other env is ${{env.other_env}}"
          
#     with:
#       ARN_Name: AWS_cert_Name
#     runs-on: [ubuntu-latest]
#     steps:
#       - name: Step1
#         run: echo "hello from job1" 
  
#       - name: Call job2 
#         uses:  shubhamPatkar/Smart-Parking/.github/workflows/job2.yml@main
       
