name: job 1

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo "hello from job1 " 
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Call job2
        uses: ./.github/workflows/job2.yml
