name: job 1

on:
  push:
    branches:
      - main

jobs:
#   job1:
#     uses: shubhamPatkar/Smart-Parking/.github/workflows/job2.yml@main
#     with:
#       jdk_version: 11
    steps:
      - name: Step1
        run: echo "hello from job1" 
  
      - name: Call job2
        uses:  shubhamPatkar/Smart-Parking/.github/workflows/job2.yml@main
       
