name: job 1

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: select the environment
        required: true
        default: qual
        options:
         - qual
         - cert
  schedule:
    - cron: '*/5 * * * *'
env:
    ARN_NAME: AWS_${{github.event.inputs.environment}}_ENV
    POOL_ENV: ${{github.event.inputs.environment}}
    other_env_key: 'OTHER_ENV_FOR_${{github.event.inputs.environment}}' 
   # other_env: '${{secrets[OTHER_ENV_FOR_${{github.event.inputs.environment}^}]}}'
    other_env: ${{secrets.OTHER_ENV_FOR_QUAL}}
   #  cust_pool: 'abc_${{secrets[OTHER_ENV_FOR_${{github.event.inputs.environment}^}]}}-java_devTools'
    suite_id_key: '${{github.event.inputs.environment}}_SUITE_ID'
   #     suite_id: ${{secrets[suite_id_key]}}
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        env:
            var:  ${{ contains(github.event.inputs.environment, 'cert') || contains(github.event.inputs.environment, 'qual') }}
            var2: true
        run: |
          if ${var} == true;
          then
          echo "Running in If"
          else
          if ${var2} == true;
          then
          echo "running in else"
          echo "ARN_NAME= AWS_CERT_ELSE_ENV" >> $GITHUB_ENV
          fi
          
          fi
          echo "Enviornment is ${{github.event_name}}"
          echo "Enviornment is ${{github.event.inputs.environment}}"
          echo "Hello from job1 ${{env.ARN_NAME}}"
          echo "Hello from job1 ${{env.POOL_ENV}}"
          echo "other env is ${{env.other_env}}"
          echo "other env is ${{env.other_env_key}}"
          echo "suite id key is ${{env.suite_id_key}}"
         # echo "suiteIdKey=${env.suite_id_key,,}" >>${GITHUB_ENV}
         # echo $suiteIdKey
         # echo "suite_id is ${{env.suite_id}}"
         # echo "cutst_pool is ${{env.cust_pool}}"
       
  job2:
    needs: job1
    if: ${{ github.event.inputs.environment == 'cert'}}
    uses:  shubhamPatkar/Smart-Parking/.github/workflows/job2.yml@main
#     secrets:
#       envPAT: 'CERT'
#     with:
#           ARN_NAME: 'CERT'
#           event-type: my-event
#           client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "test": "test message"}'
        
  job3:
    needs: job2
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: |
          echo "Enviornment is ${{github.event.inputs.environment}}"
          echo "Hello from job3 ${{env.ARN_NAME}}"
          echo "other env is ${{env.other_env}}"
          
  job4:
    needs: job3
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: |
          echo "Hello from job3 ${{env.ARN_NAME}}"
          echo "other env is ${{env.other_env}}"
          
#     with:
#       ARN_Name: AWS_cert_Name
#     runs-on: [ubuntu-latest]
#     steps:
#       - name: Step1
#         run: echo "hello from job1" 
  
#       - name: Call job2 
#         uses:  shubhamPatkar/Smart-Parking/.github/workflows/job2.yml@main
       
