name: job 2

on:
  workflow_call:
    

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo "Enviornment is in other file job2 is ${{github.event.inputs.environment}}"

