name: job 2

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: select the environment
        required: true
        default: qual
        options:
         - qual
         - cert
    

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Swt Env Variable
        env:
          envVariable: ${{ contains(github.event.inputs.environment, 'cert') }}
        run: |
          if ${envVariable} == true;
          then
          echo "Running on certify env"
          echo "ARN_NAME=AWS_CERT_ENV" >> $GITHUB_ENV
          
          else
          echo "Running on quality env"
          echo "ARN_NAME=AWS_QUAL_ENV" >> $GITHUB_ENV

          fi
      - name: print variables
        run: |
          echo "ARN_NAME value is ${{env.ARN_NAME}}"
          echo "secret value is ${{ secrets['CERT_SUITE_ID'] }}"
