name: job 2

on:
  workflow_call:
    secrets:
      SOME_SECRET:
        required: false

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo  ${{github.event.ARN_NAME}}
