name: My Workflow

on:
  push:
    branches:
      - main

env:
  MY_VARIABLE: "Hello, World!"

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display global environment variable
        run: echo "::set-env name=MY_VARIABLE::failure"

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display global environment variable
        run:  echo ${{env.MY_VARIABLE}}
