name: Multiple Jobs with Environment Variables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable for Job 1
        run: echo "ENV_VAR_JOB1=value1" >> $GITHUB_ENV

      - name: Display environment variable for Job 1
        run: echo $ENV_VAR_JOB1

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable for Job 2
        run: echo "ENV_VAR_JOB2=value2" >> $GITHUB_ENV

      - name: Display environment variable for Job 2
        run: echo $ENV_VAR_JOB1
